fail-on-severity: 'low'
allow-dependencies-licenses:
  - "pkg:pypi/numba"
  - "pkg:pypi/llvmlite"
deny-licenses:
  - 'GPL-1.0-only'
  - 'GPL-1.0-or-later'
  - 'GPL-2.0-only'
  - 'GPL-2.0-or-later'
  - 'GPL-3.0-only'
  - 'GPL-3.0-or-later'

  - 'AGPL-1.0-only'
  - 'AGPL-1.0-or-later'
  - 'AGPL-3.0-only'
  - 'AGPL-3.0-or-later'
